language: cpp

compiler:
  - gcc
  - clang

git:
  submodules: false

sudo: false

addons:
  apt:
    packages:
      - fonts-humor-sans
      - fonts-inconsolata
      - fonts-takao-gothic
      - fonts-takao-mincho
      - fonts-takao-pgothic

install: ./autogen.sh

script: ./configure && make check
